### ISSUE TITLE
纠错等级 level 参数无效

### ISSUE THREAD

**Issue by yulinyige** [StringKe/simple-qrbtf#2]
在调用 SimpleQr.base({ level: "L", content: "xxxxx" }) 方法时传递 level 参数无效，查看源码，是因为判断 icon 时不为空，默认都是设置为 “H”, 而 icon 默认不为空。如果设置 icon 为空，导致生成失败。所以，请修复下，加个条件判断。

**Comment by StringKe** [comment]
已允许第二个参数传入自定义配置合并方法，原先默认为 H 考虑加入 icon 后导致遮挡的内容过多所以提高纠错级别保证识别率
